version: '2'
services:

 phpservermonitor:
    image: scavin/phpservermonitor:3.3.2
    restart: always
    depends_on:
     - mysql
    ports:
     - 80:80
    volumes:
     - ${PWD}/config.php:/var/www/html/config.php:rw

 mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=PASSWORD
    volumes:
     - ./mysql/db-data:/var/lib/mysql
    restart: always


 phpmyadmin:
    image: corbinu/docker-phpmyadmin
    environment:
     - MYSQL_USERNAME=root
     - MYSQL_PASSWORD=PASSWORD
     - MYSQL_PORT_3306_TCP_ADDR=mysql
    depends_on:
     - mysql
     ports:
     - 81:80

